# Generated by Django 2.0.4 on 2018-04-20 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emmascrumy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalstatus',
            options={'verbose_name_plural': 'ScrumyStatus'},
        ),
        migrations.AlterModelOptions(
            name='scrumygoals',
            options={'verbose_name_plural': 'ScrumyGoals'},
        ),
        migrations.AlterModelOptions(
            name='scrumyuser',
            options={'verbose_name_plural': 'ScrumyUser'},
        ),
    ]
