# Generated by Django 2.0.4 on 2018-04-20 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emmascrumy', '0002_auto_20180420_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumyuser',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrumyuser',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
