# Generated by Django 2.0.4 on 2018-04-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emmascrumy', '0003_auto_20180420_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumygoals',
            old_name='goalstatus',
            new_name='goal_status',
        ),
        migrations.RenameField(
            model_name='scrumygoals',
            old_name='usergoals',
            new_name='user_goals',
        ),
    ]
