# Generated by Django 2.0.4 on 2018-04-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emmascrumy', '0004_auto_20180420_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumygoals',
            old_name='user_goals',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='scrumyuser',
            name='email',
        ),
    ]
