# Generated by Django 2.0.4 on 2018-04-20 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmascrumy', '0005_auto_20180420_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalstatus',
            old_name='verified',
            new_name='verify',
        ),
        migrations.RemoveField(
            model_name='goalstatus',
            name='daily_goals',
        ),
        migrations.RemoveField(
            model_name='goalstatus',
            name='weekly_goals',
        ),
        migrations.AddField(
            model_name='goalstatus',
            name='daily_target',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='goalstatus',
            name='weekly_target',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
