# Generated by Django 2.0.4 on 2018-04-21 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emmascrumy', '0006_auto_20180420_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumygoals',
            old_name='goal_status',
            new_name='status_id',
        ),
        migrations.RenameField(
            model_name='scrumygoals',
            old_name='username',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='goalstatus',
            name='daily_target',
        ),
        migrations.RemoveField(
            model_name='goalstatus',
            name='done',
        ),
        migrations.RemoveField(
            model_name='goalstatus',
            name='verify',
        ),
        migrations.RemoveField(
            model_name='goalstatus',
            name='weekly_target',
        ),
        migrations.AddField(
            model_name='goalstatus',
            name='status',
            field=models.CharField(choices=[('WT', 'Weekly Task'), ('DT', 'Daily Task'), ('V', 'Verified'), ('D', 'Done')], default='DT', max_length=50),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='task',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scrumyuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scrumyuser',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
