# Generated by Django 2.0.4 on 2018-04-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmascrumy', '0007_auto_20180421_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumyuser',
            name='roles',
            field=models.CharField(choices=[('O', 'Owner'), ('A', 'Admin'), ('QA', 'Quality Analyst'), ('D', 'Developer')], default='O', max_length=50),
        ),
    ]
