# Generated by Django 2.0.4 on 2018-04-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emmascrumy', '0008_scrumyuser_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumyuser',
            old_name='roles',
            new_name='role',
        ),
    ]
