# Generated by Django 2.0.4 on 2018-04-21 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmascrumy', '0009_auto_20180421_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalstatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scrumygoals',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scrumyuser',
            options={},
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='task_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='goalstatus',
            name='status',
            field=models.CharField(choices=[('WT', 'Weekly Task'), ('DT', 'Daily Task'), ('V', 'Verified'), ('D', 'Done')], default='Daily Task', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
