# Generated by Django 2.0.4 on 2018-04-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emmascrumy', '0012_auto_20180425_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumygoals',
            name='task',
        ),
    ]
